#!/usr/bin/env bash
export IMAGE
IMAGE=$( oc status | grep '^pod')

function version() {
  # get version from image (major.minor.micro, e.g. v4.11.0)
  local extracted
  extracted=$(sed -n -r -e 's/.*(([[:digit:]])+\.([[:digit:]])+\.([[:digit:]])+).*/\1/p' <<< "$IMAGE")

  if [ -n "${extracted}" ]; then
    version="v${extracted}"
  else
    version="0.0.0-unknown"
  fi

  echo "${version}"
}

function imageId() {
  # get image id (e.g. repository@digest )
  imageId=$(sed -r -e 's/^pod.*runs //' <<< "$IMAGE" | awk '{print $2}')

  # if image_id is not found, use Unknown
  [ -z "${imageId}" ] && imageId="Unknown-Image"

  echo "${imageId}"

}